### ISSUE TITLE
Atualizar Perfil 

### ISSUE THREAD

**Issue by jotadepaula** [Mobfrete-mobile/mobfrete#5]
Deixar tela de perfil funcional atualizando os dados do usuário

**Comment by maxgoulart** [comment]
Perfil, sem misterio
Chamar o servico "/rest/usuario/getUsuarioInfo"
Vai te retornar um json da entidade Usuario

Atualizar perfil
Chamar o servico "/rest/usuario/atualizarUsuario"

Ficar atento, usuarios do tipo prestador de serviço os dados da moto, van e caminhao sao diferentes
A tela nao contempla estes dados, deixei pra fazer na hora de integrar.. pensa ai numa melhor solucao
se é fazer 4 telas de perfil ou ocultar e exibir campos em tempo de execucao
