### ISSUE TITLE
Favoritos

### ISSUE THREAD

**Issue by jotadepaula** [Mobfrete-mobile/mobfrete#6]
Deixar rotina de buscar favoritos e Deletar favortios funcionando

**Comment by maxgoulart** [comment]
Quando o usuario selecionar o switch "Gravar endereço de coleta", na tela de chamado moto boy, tem que disparar a chamada "/rest/usuario/addFavorito" 
Endereco = logradouro
nº = numero
complemento = complemento
referencia = referencia
Nome responsavel pela entrega = responsavel
telefone responsavel = telefone

Deletar favoritos, sem misterios.
chamar o servico  "/rest/usuario/removeFavorito/ID_FAVORITO"

Buscar favoritos, sem misterios
chamar o servico "/rest/usuario/getFavorito"
vai retornar uma lista da entidade Favorito
